version: "3"

services:
  dind:
    image: nickdlk/dind 
    build: .
    privileged: true
    container_name: dind
    volumes:
      - /usr/dind/docker:/var/lib/docker:Z
      - /root/projects/web:/web:Z
      - ./ssh:/root/.ssh:Z
      - ./vscode-server:/root/.vscode-server:Z
    ports:
      - "2022:2022"
    environment:
      USER: dind
      PASSWORD: dind

